version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:9000"
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite

